dbConfig:
  host: localhost
  port: "5432"
  user: postgres
  password: yamanashi@412907
  dbname: postgres
  sslmode: disable
  timezone: Asia/Tokyo

redisConfig:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100


LogConfig:
  backend:
    filename: backend.log
    maxsize: 100
    maxbackups: 10
    maxage: 30
    compress: false
  access:
    filename: access.log
    maxsize: 100
    maxbackups: 10
    maxage: 30
    compress: true
  level: info
