dbConfig:
  host: localhost
  port: "5432"
  user: postgres
  password: yamanashi@412907
  dbname: postgres
  sslmode: disable
  timezone: Asia/Tokyo

redisConfig:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100
